global_functions added and temperatur script workable now

diff --git a/workstation/cluster_temperature b/workstation/cluster_temperature
--- a/workstation/cluster_temperature
+++ b/workstation/cluster_temperature
@@ -1,8 +1,68 @@
 #!/bin/bash
 
-# We need some functions from global_functions. When you mounted the server module's root partition with the provided script these functions were made available already.
+# Usage: $0 singleNode (integer in range 1 to 60) or just $0 for all nodes
+
+# Used to iterate over "all" nodes later
+first_node=1
+last_node=60
+
+# Username to ssh into the nodes
+username="pi"
+
+module=${1:-"all"}
+if [[ $module != "all" ]]; then
+	number='^[0-9]+$'
+	if ! [[ "$module" =~ $number && $module -gt $(( first_node - 1 )) && $module -lt $(( last_node + 1 )) ]]; then
+		echo "Invalid input."
+		exit 1
+	fi
+fi
+
+# Path to global functions
+GFUNC="../global_functions"
+
+# Global functions are needed in this script
+source "$GFUNC"
+if [[ $? != 0 ]]; then
+	echo "Global functions are required for this script."
+	exit 1
+fi
+
+# Receives temperature for node $1 and saves it into an ass. array
+declare -A tempNodes
+function get_temp_for_node {
+	current_ip=$(get_ip_for_node $1)
+	# echo $current_ip
+	current_temp=$(ssh $username@$current_ip 'cpu_temp=$(cat /sys/class/thermal/thermal_zone0/temp | sed "s/...$/.&/"); gpu_temp=$(/opt/vc/bin/vcgencmd measure_temp | sed "s/[^0-9.]//g"); echo $cpu_temp/$gpu_temp')
+	# current_temp=$(ssh $username@$current_ip 'vcgencmd measure_temp')
+	tempNodes[$1]=$current_temp
+	echo $current_temp
+}
 
 
+# Headline
+
+# Terminal properties. We need 5 rows and 15 columns
+width=$(tput cols)
+width=$(( width - width % 5 ))
+
+fifth=$(( width / 5 ))
+printf '%-*s%-*s%-*s%-*s%-*s\n' $(( fifth / 2 )) "" $fifth "A" $fifth "B" $fifth "C" $fifth "D"
+
+for (( col=1; col<=15; col++ )); do
+
+	printf '%-*x' $(( fifth / 2 )) $col
+	# printf '%-*s' $fifth $line
+	for (( row=0; row<4; row++ )); do
+		current_node=$(( col + row * 15 ))
+		
+		current_temp=$(get_temp_for_node $current_node)
+		printf '%-*s' $fifth $current_temp
+	
+	done
+	printf '\n'
+done
+exit
 
 # takes $1 array of integers and echoes the $2 greatest elements
 function find_max {
@@ -10,11 +70,11 @@ function find_max {
 	
 }
 
-username="pi"
+
 currentip="10.42.0."
 
-startnode=48
-endnode=60
+startnode=30
+endnode=32
 count=$(( 1 + (endnode-startnode) ))
 
 declare -A nodes
